In [1]:
import numpy as np
import pandas as pd

In [5]:
ud=pd.read_csv("dataset/udemy.csv",parse_dates=['published_timestamp'])

In [19]:
ud.shape

(3672, 12)

# 1. Display Top 10 Rows of The Dataset?

In [7]:
ud.head(10)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18 20:58:58+00:00,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09 16:34:20+00:00,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19 19:26:30+00:00,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30 20:07:24+00:00,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13 14:57:18+00:00,Business Finance
5,192870,Trading Penny Stocks: A Guide for All Levels I...,https://www.udemy.com/trading-penny-stocks-a-g...,True,150,9221,138,25,All Levels,3.0,2014-05-02 15:13:30+00:00,Business Finance
6,739964,Investing And Trading For Beginners: Mastering...,https://www.udemy.com/investing-and-trading-fo...,True,65,1540,178,26,Beginner Level,1.0,2016-02-21 18:23:12+00:00,Business Finance
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5,2015-01-30 22:13:03+00:00,Business Finance
8,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5,2015-05-28 00:14:03+00:00,Business Finance
9,1167710,The Only Investment Strategy You Need For Your...,https://www.udemy.com/the-only-investment-stra...,True,200,827,14,15,All Levels,1.0,2017-04-18 18:13:32+00:00,Business Finance

# 2. Check Last 5 Rows of The Dataset?

In [5]:
ud.tail(5)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

# 3. Find Shape of Our Dataset (Number of Rows And Number of Columns)?

In [6]:
ud.shape[0]

3678

In [7]:
ud.shape[1]

12

# 4. Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement?

In [8]:
ud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3678 entries, 0 to 3677
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3678 non-null   int64
 1   course_title         3678 non-null   object
 2   url                  3678 non-null   object
 3   is_paid              3678 non-null   bool
 4   price                3678 non-null   int64
 5   num_subscribers      3678 non-null   int64
 6   num_reviews          3678 non-null   int64
 7   num_lectures         3678 non-null   int64
 8   level                3678 non-null   object
 9   content_duration     3678 non-null   float64
 10  published_timestamp  3678 non-null   datetime64[ns, UTC]
 11  subject              3678 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), float64(1), int64(5), object(4)
memory usage: 319.8+ KB

# 5. Check Null Values In The Dataset?

In [11]:
ud.isnull().sum().any()

np.False_

# 6. Check For Duplicate Data and Drop Them?

In [17]:
ud.duplicated().sum().any()

np.False_

In [14]:
ud[ud.duplicated()]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
787,837322,Essentials of money value: Get a financial Life !,https://www.udemy.com/essentials-of-money-value/,True,20,0,0,20,All Levels,0.616667,2016-05-16 18:28:30+00:00,Business Finance
788,1157298,Introduction to Forex Trading Business For Beg...,https://www.udemy.com/introduction-to-forex-tr...,True,20,0,0,27,Beginner Level,1.500000,2017-04-23 16:19:01+00:00,Business Finance
894,1035638,Understanding Financial Statements,https://www.udemy.com/understanding-financial-...,True,25,0,0,10,All Levels,1.000000,2016-12-15 14:56:17+00:00,Business Finance
1100,1084454,CFA Level 2- Quantitative Methods,https://www.udemy.com/cfa-level-2-quantitative...,True,40,0,0,35,All Levels,5.500000,2017-07-02 14:29:35+00:00,Business Finance
1473,185526,MicroStation - Células,https://www.udemy.com/microstation-celulas/,True,20,0,0,9,Beginner Level,0.616667,2014-04-15 21:48:55+00:00,Graphic Design
2561,28295,Learn Web Designing & HTML5/CSS3 Essentials in...,https://www.udemy.com/build-beautiful-html5-we...,True,75,43285,525,24,All Levels,4.000000,2013-01-03 00:55:31+00:00,Web Development

In [15]:
ud.drop_duplicates(inplace=True)

In [16]:
ud.duplicated().any()

np.False_

In [18]:
ud.shape

(3672, 12)

# 7. What are all different subjects for which Udemy is offering courses ?

In [22]:
ud.subject.unique()

array(['Business Finance', 'Graphic Design', 'Musical Instruments',
       'Web Development'], dtype=object)

In [34]:
ud

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

# 8. Find Out Number of Courses Per Subjects?

In [35]:
ud.groupby('subject')['course_id'].count()

subject
Business Finance       1195
Graphic Design          603
Musical Instruments     680
Web Development        1200
Name: course_id, dtype: int64

# 9.Show all the courses which are Free of Cost?

In [37]:
ud[ud['is_paid']==False]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
95,1148774,Options Trading 101: The Basics,https://www.udemy.com/options-trading-101-the-...,False,0,1514,66,11,Beginner Level,0.550000,2017-03-23T22:19:57Z,Business Finance
103,133536,Stock Market Investing for Beginners,https://www.udemy.com/the-beginners-guide-to-t...,False,0,50855,2698,15,Beginner Level,1.500000,2013-12-25T19:53:34Z,Business Finance
106,265960,Fundamentals of Forex Trading,https://www.udemy.com/fundamentals-of-forex-tr...,False,0,17160,620,23,All Levels,1.000000,2014-08-29T20:10:38Z,Business Finance
108,923616,Website Investing 101 - Buying & Selling Onlin...,https://www.udemy.com/cash-flow-website-invest...,False,0,6811,151,51,All Levels,2.000000,2016-08-05T17:03:15Z,Business Finance
112,191854,Stock Market Foundations,https://www.udemy.com/how-to-invest-in-the-sto...,False,0,19339,794,9,Beginner Level,2.000000,2014-03-31T21:35:06Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3638,155640,Building a Search Engine in PHP & MySQL,https://www.udemy.com/creating-a-search-engine...,False,0,10110,379,12,All Levels,2.500000,2014-02-03T18:07:52Z,Web Development
3643,366720,CSS Image filters - The modern web images colo...,https://www.udemy.com/super-awesome-images-wit...,False,0,6315,53,16,All Levels,1.500000,2014-12-10T19:43:40Z,Web Development
3651,1079078,Drupal 8 Site Building,https://www.udemy.com/drupal-8-site-building/,False,0,1942,23,48,All Levels,4.500000,2017-05-02T05:15:52Z,Web Development
3665,21386,Beginner Photoshop to HTML5 and CSS3,https://www.udemy.com/psd-html5-css3/,False,0,73110,1716,22,All Levels,2.000000,2012-07-27T12:54:57Z,Web Development
3668,270976,A how to guide in HTML,https://www.udemy.com/a-how-to-guide-in-html/,False,0,7318,205,8,Beginner Level,0.583333,2014-08-10T20:19:10Z,Web Development

# 10.Show all the courses which are Paid?

In [38]:
ud[ud['is_paid']==True]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

# 11. Display The Count of Paid and Free Courses?

In [21]:
ud[ud['is_paid']==True].shape[0]

3362

In [22]:
ud['is_paid'].value_counts()

is_paid
True     3362
False     310
Name: count, dtype: int64

In [45]:
ud[ud['is_paid']==False].shape[0]

310

# 12. For Which Levels, Udemy Courses Providing The Courses?

In [59]:
ud['level'].unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

In [23]:
ud['level'].value_counts()

level
All Levels            1925
Beginner Level        1268
Intermediate Level     421
Expert Level            58
Name: count, dtype: int64

# 13.Which are Top Selling Courses ?

In [58]:
ud.sort_values(by='num_subscribers',ascending=False).head(1)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2827,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,False,0,268923,8629,45,All Levels,10.5,2013-02-14T07:03:41Z,Web Development

# 14.Which are Least Selling Courses ?

In [60]:
ud.sort_values(by='num_subscribers',ascending=True).head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
777,1215926,Kickstarter success in 5 easy steps,https://www.udemy.com/kickstarter-success-in-5...,True,20,0,0,12,All Levels,0.516667,2017-05-16T14:55:28Z,Business Finance
781,975910,How to achieve personal transformation,https://www.udemy.com/learnhowtocreatewealth/,True,20,0,0,10,All Levels,0.533333,2016-12-22T00:28:07Z,Business Finance
779,1249146,Planning and Executing a Financial Statement A...,https://www.udemy.com/planning-executing-finan...,True,50,0,0,9,Intermediate Level,2.000000,2017-06-29T23:18:51Z,Business Finance
778,1035638,Understanding Financial Statements,https://www.udemy.com/understanding-financial-...,True,25,0,0,10,All Levels,1.000000,2016-12-15T14:56:17Z,Business Finance
1569,726314,Create Beautiful Image Maps for Your Website,https://www.udemy.com/how-to-create-hotspot-im...,True,20,0,0,8,Intermediate Level,0.616667,2016-01-18T17:56:36Z,Graphic Design

# 15.Show all courses of Graphic Design where the price is below 100 ?

In [77]:
ud[(ud['subject']=='Graphic Design')&(ud['price']<100)]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
1196,1197206,Illustrator CC MasterClass,https://www.udemy.com/illustrator-cc-masterclass/,True,95,462,50,86,All Levels,12.0,2017-05-02T16:41:21Z,Graphic Design
1198,1219520,Adobe Illustrator T-Shirt Design for Merch by ...,https://www.udemy.com/merchbyamazondesign/,True,20,390,44,15,All Levels,1.0,2017-06-13T20:41:14Z,Graphic Design
1202,28556,Discover How to Draw and paint Comics,https://www.udemy.com/learn-to-draw-and-paint/,True,65,8901,424,85,All Levels,62.0,2012-11-21T22:03:54Z,Graphic Design
1203,317278,Typographic Logos: Typography and Lettering fo...,https://www.udemy.com/typographic-logos-typogr...,True,25,4235,427,20,Intermediate Level,1.5,2014-10-16T19:30:01Z,Graphic Design
1204,573064,Photoshop in Ease: Create World Amazing Graph...,https://www.udemy.com/photoshop-knights-become...,True,20,14440,182,26,All Levels,3.0,2015-08-13T21:17:34Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...,...
1793,456388,Adobe Photoshop CC | The Essential Guide,https://www.udemy.com/adobe-photoshop-cc-the-e...,True,20,254,5,81,All Levels,4.5,2015-05-12T00:19:27Z,Graphic Design
1794,955242,Learn to Composite a 2D Action Shot in Photoshop,https://www.udemy.com/3dmotive-learn-to-compos...,True,20,40,2,8,Beginner Level,1.5,2016-09-10T21:38:26Z,Graphic Design
1795,496430,Infographic Design: How To Create Your Own Inf...,https://www.udemy.com/infographic-design-how-t...,True,20,84,8,13,All Levels,2.0,2015-05-12T20:38:58Z,Graphic Design
1796,793246,Autodesk Inventor 2016 : Complete Guide,https://www.udemy.com/learn-autodesk-inventor-...,True,20,23,4,83,Beginner Level,7.5,2016-03-22T20:35:56Z,Graphic Design
1797,547190,Amazing Graphic Design for Beginners,https://www.udemy.com/amazing-graphic-design-f...,True,20,32,10,5,Beginner Level,0.7,2015-07-08T19:58:01Z,Graphic Design

# 16. Find Most Popular Course Title?

In [76]:
ud['course_title'].value_counts().head(1)

course_title
Creating an animated greeting card via Google Slides    3
Name: count, dtype: int64

# 17. Display 10 Most Popular Courses As Per Number of Subscribers?

In [84]:
ud.sort_values(by='num_subscribers',ascending=False).head(10)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2827,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,False,0,268923,8629,45,All Levels,10.5,2013-02-14T07:03:41Z,Web Development
3032,59014,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,False,0,161029,279,27,Beginner Level,3.5,2013-06-09T15:51:55Z,Web Development
3230,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,True,200,121584,27445,342,All Levels,43.0,2015-11-02T21:13:27Z,Web Development
2783,173548,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,False,0,120291,5924,30,Beginner Level,3.0,2014-04-08T16:21:30Z,Web Development
3232,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,True,200,114512,22412,304,All Levels,30.5,2016-03-08T22:28:36Z,Web Development
1896,19421,Free Beginner Electric Guitar Lessons,https://www.udemy.com/beginner-electric-guitar...,False,0,101154,1042,95,Beginner Level,4.5,2012-06-15T17:00:33Z,Musical Instruments
2589,473160,Web Design for Web Developers: Build Beautiful...,https://www.udemy.com/web-design-secrets/,False,0,98867,6512,20,All Levels,3.0,2015-04-13T18:29:47Z,Web Development
2619,94430,Learn Javascript & JQuery From Scratch,https://www.udemy.com/learn-javascript-jquery-...,True,30,84897,2685,10,All Levels,2.0,2013-10-10T15:19:29Z,Web Development
3289,130064,Practical PHP: Master the Basics and Code Dyna...,https://www.udemy.com/code-dynamic-websites/,False,0,83737,4598,45,All Levels,6.5,2014-07-19T03:02:05Z,Web Development
3247,364426,JavaScript: Understanding the Weird Parts,https://www.udemy.com/understand-javascript/,True,175,79612,16976,85,All Levels,11.5,2015-03-12T23:19:54Z,Web Development

# 18. Find Total Number of Courses Related To Python?

In [24]:
ud[ud['course_title'].str.contains('Python')].shape[0]

29

# 19. Display 10 Most Popular Python Courses As Per Number of Subscribers?

In [27]:
ud[ud['course_title'].str.contains('Python',case=False)].sort_values(by='num_subscribers',ascending=False).head(10)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2497,16646,Web Programming with Python,https://www.udemy.com/web-programming-with-pyt...,True,50,35267,217,53,All Levels,4.0,2012-04-25 00:01:43+00:00,Web Development
2570,47963,"Coding for Entrepreneurs: Learn Python, Django...",https://www.udemy.com/coding-for-entrepreneurs/,True,195,23412,799,251,All Levels,45.0,2013-04-08 00:46:14+00:00,Web Development
2528,391546,Learn Python and Django: Payment Processing,https://www.udemy.com/learn-django-code-accept...,True,70,17714,198,23,All Levels,3.5,2015-02-09 15:37:56+00:00,Web Development
3200,822444,Python and Django Full Stack Web Developer Boo...,https://www.udemy.com/python-and-django-full-s...,True,200,11832,1883,191,All Levels,31.5,2017-02-24 18:40:55+00:00,Web Development
3507,394832,Fun and creative web engineering with Python a...,https://www.udemy.com/web-engineering-with-pyt...,False,0,10917,319,25,All Levels,2.0,2015-06-09 19:51:50+00:00,Web Development
2553,938560,The Complete Ethical Hacking Course 2.0: Pytho...,https://www.udemy.com/penetration-testing-ethi...,True,195,7827,268,66,All Levels,11.0,2016-09-26 15:08:29+00:00,Web Development
3138,631128,Complete Python Web Course: Build 8 Python Web...,https://www.udemy.com/the-complete-python-web-...,True,110,7489,941,173,All Levels,16.0,2015-11-08 20:57:35+00:00,Web Development
3197,76052,Try Django 1.9 | Build a Blog and Learn Python...,https://www.udemy.com/try-django/,True,50,7407,172,147,All Levels,20.0,2014-03-04 07:12:21+00:00,Web Development
2681,477702,Python for Beginners: Python Programming Langu...,https://www.udemy.com/python-course/,True,150,6153,125,84,Beginner Level,5.0,2015-06-14 18:18:57+00:00,Web Development
3203,970600,REST APIs with Flask and Python,https://www.udemy.com/rest-api-flask-and-python/,True,110,5151,737,115,Intermediate Level,12.5,2016-11-06 19:00:38+00:00,Web Development

# 20.What are courses that published in year 2015 ?

In [28]:
ud['published_timestamp']=pd.to_datetime(ud['published_timestamp'])

In [30]:
ud['Year']=ud['published_timestamp'].dt.year

In [32]:
ud[ud.Year==2015]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5,2015-01-30 22:13:03+00:00,Business Finance,2015
8,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5,2015-05-28 00:14:03+00:00,Business Finance,2015
10,592338,Forex Trading Secrets of the Pros With Amazon'...,https://www.udemy.com/trading-with-amazons-aws...,True,200,4284,93,76,All Levels,5.0,2015-09-11 16:47:02+00:00,Business Finance,2015
15,504036,Short Selling: Learn To Sell Stocks Before The...,https://www.udemy.com/short-selling-learn-to-s...,True,75,2276,106,19,Intermediate Level,1.5,2015-06-22 21:18:35+00:00,Business Finance,2015
17,564966,The Complete Chart Pattern Trading Course: A P...,https://www.udemy.com/make-money-trading-stock...,True,200,2666,115,52,All Levels,4.0,2015-08-10 21:07:35+00:00,Business Finance,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3659,577796,"Simple Javascript: Learn by Doing, Beginners W...",https://www.udemy.com/simple-javascript-learn-...,True,25,2753,10,18,All Levels,2.0,2015-09-07 17:55:11+00:00,Web Development,2015
3667,523216,The Fastest Way to Create a Website Using Godaddy,https://www.udemy.com/create-your-own-website/,True,30,1454,14,12,Beginner Level,0.5,2015-11-09 20:44:25+00:00,Web Development,2015
3669,679992,Building Better APIs with GraphQL,https://www.udemy.com/building-better-apis-wit...,True,50,555,89,16,All Levels,2.5,2015-11-29 22:02:02+00:00,Web Development,2015
3671,667122,Build A Stock Downloader With Visual Studio 20...,https://www.udemy.com/csharpyahoostockdownloader/,True,20,436,36,22,Intermediate Level,1.5,2015-11-19 17:22:47+00:00,Web Development,2015
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30 16:41:42+00:00,Web Development,2015

In [29]:
ud[ud['published_timestamp'].dt.year==2015]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5,2015-01-30 22:13:03+00:00,Business Finance
8,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5,2015-05-28 00:14:03+00:00,Business Finance
10,592338,Forex Trading Secrets of the Pros With Amazon'...,https://www.udemy.com/trading-with-amazons-aws...,True,200,4284,93,76,All Levels,5.0,2015-09-11 16:47:02+00:00,Business Finance
15,504036,Short Selling: Learn To Sell Stocks Before The...,https://www.udemy.com/short-selling-learn-to-s...,True,75,2276,106,19,Intermediate Level,1.5,2015-06-22 21:18:35+00:00,Business Finance
17,564966,The Complete Chart Pattern Trading Course: A P...,https://www.udemy.com/make-money-trading-stock...,True,200,2666,115,52,All Levels,4.0,2015-08-10 21:07:35+00:00,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3659,577796,"Simple Javascript: Learn by Doing, Beginners W...",https://www.udemy.com/simple-javascript-learn-...,True,25,2753,10,18,All Levels,2.0,2015-09-07 17:55:11+00:00,Web Development
3667,523216,The Fastest Way to Create a Website Using Godaddy,https://www.udemy.com/create-your-own-website/,True,30,1454,14,12,Beginner Level,0.5,2015-11-09 20:44:25+00:00,Web Development
3669,679992,Building Better APIs with GraphQL,https://www.udemy.com/building-better-apis-wit...,True,50,555,89,16,All Levels,2.5,2015-11-29 22:02:02+00:00,Web Development
3671,667122,Build A Stock Downloader With Visual Studio 20...,https://www.udemy.com/csharpyahoostockdownloader/,True,20,436,36,22,Intermediate Level,1.5,2015-11-19 17:22:47+00:00,Web Development
3675,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5,2015-12-30 16:41:42+00:00,Web Development

# 21. Display Category-Wise Count of Posted Subjects [Year Wise] ?

In [35]:
ud.groupby(ud['published_timestamp'].dt.year)['subject'].value_counts()

published_timestamp  subject
2011                 Web Development          5
2012                 Web Development         19
                     Graphic Design          10
                     Musical Instruments     10
                     Business Finance         6
2013                 Business Finance        84
                     Web Development         55
                     Musical Instruments     39
                     Graphic Design          23
2014                 Business Finance       192
                     Musical Instruments    120
                     Web Development        113
                     Graphic Design          65
2015                 Business Finance       339
                     Web Development        336
                     Musical Instruments    171
                     Graphic Design         168
2016                 Web Development        448
                     Business Finance       347
                     Musical Instruments    228
                     Graphic Design         181
2017                 Business Finance       223
                     Web Development        223
                     Graphic Design         155
                     Musical Instruments    112
Name: count, dtype: int64

# 22.What are the Max. Number of Subscribers for Each Level of courses ?

In [36]:
ud.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64